### ISSUE TITLE
MFTBundle (en)

### ISSUE THREAD

**Issue by AxelANGENAULT** [AriiPortal/MFTBundle#1]
Le module "File transferts" n'est pas disponible en anglais.
Une erreur Symfony est remontée par le portail à cette adresse : http://Arii/app_dev.php/mft/en/
[MFT_en.pdf](https://github.com/AriiPortal/MFTBundle/files/95938/MFT_en.pdf)

**Comment by AriiPortal** [comment]
Il y a 2 choses différentes:
- Le PDF contient un message sur une route non définie, cette route dans le module Admin. Il faut mettre à jour ce module.
- La traduction en anglais n'est pas un problème de dev mais bel et bien de traduction. Pour ajouter une langue il suffit de remplir le fichier MFTBundle/Resources/translations/messages.en.yml
