### ISSUE TITLE
Popup : http://10.0.0.19/app_dev.php/mft/en/operation/form.json

### ISSUE THREAD

**Issue by AxelANGENAULT** [AriiPortal/MFTBundle#3]
Bonjour,

Un pop-up s'affiche systématiquement à l'ouverture de la page `operation` du module MFT,
ce n'est peut-être pas bloquant, je n'ai pas encore testé avec des traitements.
 Je n'ai pas plus d'informations (malgré connexion avec `app_dev`).

![mft_popup](https://cloud.githubusercontent.com/assets/11269587/12557432/fc41959c-c38a-11e5-9c0a-a4972555e565.png)

**Comment by AxelANGENAULT** [comment]
Il m'est de plus impossible d'accédé à la page `Deliveries` depuis le menu du module MFT
![deliveries](https://cloud.githubusercontent.com/assets/11269587/12557907/55871eae-c38d-11e5-8650-641ef174ca3d.png)

**Comment by AriiPortal** [comment]
Ce module est en plein développement.
Un peu de patience.

**Comment by AriiPortal** [comment]
Le module est maintenant proposé en bêta et testé en conditions réelles.
